from enum import Enum
from pydantic import BaseModel, Field


class SignalType(str, Enum):
    metric = "metric"
    log = "log"
    deploy = "deploy"
    trace = "trace"


class Signal(BaseModel):
    """An observed signal acting as evidence."""

    source_id: str
    signal_class: str = Field(
        default="observed",
        description="The class of the claim, e.g. 'observed', 'retrieved', 'inferred'",
    )
    type: SignalType
    text: str
    timestamp: str | None = Field(default=None, alias="observed_at")

    # We populate model_config to allow populating by either alias or field name
    model_config = {"populate_by_name": True}


class Hypothesis(BaseModel):
    """The root cause hypothesis generated by the Investigator."""

    text: str
    confidence: float = Field(ge=0.0, le=1.0)
    grounded_in: list[str]
    contradicted_by: list[str] = Field(default_factory=list)


class CandidateRunbook(BaseModel):
    """A retrieved procedure from the Knowledge Vault."""

    chunk_id: str
    runbook_id: str
    title: str
    service: str
    owner: str = ""
    last_verified: str = ""
    eligibility: str = "eligible"
    score: float
